import 'package:get/get.dart';

class Constants {
  
  static const List<Map<String, dynamic>> nationCode = [
    {"label": "Afghanistan", "value": "93", "labelKR": "아프가니스탄", "labelJP": "アフガニスタン", "labelCN": "阿富汗", "labelVN": "Afghanistan", "labelTH": "อัฟกานิสถาน", "labelAR": "أفغانستان"}
    { "label": "Albania", "value": "355", "labelKR": "알바니아", "labelJP": "アルバニア", "labelCN": "阿尔巴尼亚", "labelVN": "An-ba-ni", "labelTH": "แอลเบเนีย", "labelAR": "ألبانيا" },
    { "label": "Algeria", "value": "213", "labelKR": "알제리", "labelJP": "アルジェリア", "labelCN": "阿尔及利亚", "labelVN": "An-giê-ri", "labelTH": "แอลจีเรีย", "labelAR": "الجزائر" },
    { "label": "American Samoa", "value": "1684", "labelKR": "아메리칸 사모아", "labelJP": "アメリカ領サモア", "labelCN": "美属萨摩亚", "labelVN": "Samoa Mỹ", "labelTH": "อเมริกันซามัว", "labelAR": "ساموا الأمريكية" },
    { "label": "Andorra", "value": "376", "labelKR": "안도라", "labelJP": "アンドラ", "labelCN": "安道尔", "labelVN": "An-đô-ra", "labelTH": "อันดอร์รา", "labelAR": "أندورا" },
    { "label": "Angola", "value": "244", "labelKR": "앙골라", "labelJP": "アンゴラ", "labelCN": "安哥拉", "labelVN": "Ăng-gô-la", "labelTH": "แองโกลา", "labelAR": "أنغولا" },
    { "label": "Anguilla", "value": "1264", "labelKR": "앙길라", "labelJP": "アンギラ", "labelCN": "安圭拉", "labelVN": "Ăng-gu-la", "labelTH": "แองกวิลลา", "labelAR": "أنغيلا" },
    { "label": "Antigua and Barbuda", "value": "1268", "labelKR": "앤티가 바부다", "labelJP": "アンティグア・バーブーダ", "labelCN": "安提瓜和巴布达", "labelVN": "An-ti-gua và Barbuda", "labelTH": "แอนติกาและบาร์บูดา", "labelAR": "أنتيغوا وبربودا" },
    { "label": "Argentina", "value": "54", "labelKR": "아르헨티나", "labelJP": "アルゼンチン", "labelCN": "阿根廷", "labelVN": "Ác-hen-ti-na", "labelTH": "อาร์เจนตินา", "labelAR": "الأرجنتين" },
    { "label": "Armenia", "value": "374", "labelKR": "아르메니아", "labelJP": "アルメニア", "labelCN": "亚美尼亚", "labelVN": "Ác-mê-ni-a", "labelTH": "อาร์เมเนีย", "labelAR": "أرمينيا" },
    { "label": "Aruba", "value": "297", "labelKR": "아루바", "labelJP": "アルバ", "labelCN": "阿鲁巴", "labelVN": "A-ru-ba", "labelTH": "อารูบา", "labelAR": "أروبا" },
    { "label": "Australia", "value": "61", "labelKR": "호주", "labelJP": "オーストラリア", "labelCN": "澳大利亚", "labelVN": "Úc", "labelTH": "ออสเตรเลีย", "labelAR": "أستراليا" },
    { "label": "Austria", "value": "43", "labelKR": "오스트리아", "labelJP": "オーストリア", "labelCN": "奥地利", "labelVN": "Áo", "labelTH": "ออสเตรีย", "labelAR": "النمسا" },
    { "label": "Azerbaijan", "value": "994", "labelKR": "아제르바이잔", "labelJP": "アゼルバイジャン", "labelCN": "阿塞拜疆", "labelVN": "A-déc-bai-gian", "labelTH": "อาเซอร์ไบจาน", "labelAR": "أذربيجان" },
    { "label": "Bahamas", "value": "1242", "labelKR": "바하마", "labelJP": "バハマ", "labelCN": "巴哈马", "labelVN": "Ba-ha-ma", "labelTH": "บาฮามาส", "labelAR": "جزر البهاما" },
    { "label": "Bahrain", "value": "973", "labelKR": "바레인", "labelJP": "バーレーン", "labelCN": "巴林", "labelVN": "Ba-ranh", "labelTH": "บาห์เรน", "labelAR": "البحرين" },
    { "label": "Bangladesh", "value": "880", "labelKR": "방글라데시", "labelJP": "バングラデシュ", "labelCN": "孟加拉国", "labelVN": "Băng-la-đét", "labelTH": "บังกลาเทศ", "labelAR": "بنغلاديش" }
    { "label": 'Barbados', "value": '1246', "labelKR": '바베이도스', "labelJP": "バルバドス", "labelCN": "巴巴多斯", "labelVN": "Ba-ba-đốt", "labelTH": "บาร์เบโดส", "labelAR": "باربادوس" },
    { "label": 'Belarus', "value": '375', "labelKR": '벨라루스', "labelJP": "ベラルーシ", "labelCN": "白俄罗斯", "labelVN": "Bê-la-rút", "labelTH": "เบลารุส", "labelAR": "بيلاروس" },
    { "label": 'Belgium', "value": '32', "labelKR": '벨기에', "labelJP": "ベルギー", "labelCN": "比利时", "labelVN": "Bỉ", "labelTH": "เบลเยียม", "labelAR": "بلجيكا" },
    { "label": 'Belize', "value": '501', "labelKR": '벨리즈', "labelJP": "ベリーズ", "labelCN": "伯利兹", "labelVN": "Bê-li-xê", "labelTH": "เบลีซ", "labelAR": "بليز" },
    { "label": 'Benin', "value": '229', "labelKR": '베냉', "labelJP": "ベナン", "labelCN": "贝宁", "labelVN": "Bê-nanh", "labelTH": "เบนิน", "labelAR": "بنين" },
    { "label": 'Bermuda', "value": '1441', "labelKR": '버뮤다', "labelJP": "バミューダ", "labelCN": "百慕大", "labelVN": "Béc-mu-đa", "labelTH": "เบอร์มิวดา", "labelAR": "برمودا" },
    { "label": 'Bhutan', "value": '975', "labelKR": '부탄', "labelJP": "ブータン", "labelCN": "不丹", "labelVN": "Bu-tan", "labelTH": "ภูฏาน", "labelAR": "بوتان" },
    { "label": 'Bolivia', "value": '591', "labelKR": '볼리비아', "labelJP": "ボリビア", "labelCN": "玻利维亚", "labelVN": "Bô-li-vi-a", "labelTH": "โบลิเวีย", "labelAR": "بوليفيا" },
    { "label": 'Bosnia and Herzegovina', "value": '387', "labelKR": '보스니아 헤르체고비나', "labelJP": "ボスニア・ヘルツェゴビナ", "labelCN": "波斯尼亚和黑塞哥维那", "labelVN": "Bô-xni-a và Héc-xê-gô-vi-na", "labelTH": "บอสเนียและเฮอร์เซโกวีนา", "labelAR": "البوسنة والهرسك" },
    { "label": 'Botswana', "value": '267', "labelKR": '보츠와나', "labelJP": "ボツワナ", "labelCN": "博茨瓦纳", "labelVN": "Bốt-xoa-na", "labelTH": "บอตสวานา", "labelAR": "بوتسوانا" },
    { "label": 'Brazil', "value": '55', "labelKR": '브라질', "labelJP": "ブラジル", "labelCN": "巴西", "labelVN": "Bra-xin", "labelTH": "บราซิล", "labelAR": "البرازيل" },
    { "label": 'Brunei', "value": '673', "labelKR": '브루나이', "labelJP": "ブルネイ", "labelCN": "文莱", "labelVN": "Bru-nây", "labelTH": "บรูไน", "labelAR": "بروناي" },
    { "label": 'Bulgaria', "value": '359', "labelKR": '불가리아', "labelJP": "ブルガリア", "labelCN": "保加利亚", "labelVN": "Bun-ga-ri", "labelTH": "บัลแกเรีย", "labelAR": "بلغاريا" },
    { "label": 'Burkina Faso', "value": '226', "labelKR": '부르키나파소', "labelJP": "ブルキナファソ", "labelCN": "布基纳法索", "labelVN": "Buốc-ki-na Pha-xô", "labelTH": "บูร์กินาฟาโซ", "labelAR": "بوركينا فاسو" },
    { "label": 'Burundi', "value": '257', "labelKR": '부룬디', "labelJP": "ブルンジ", "labelCN": "布隆迪", "labelVN": "Bu-run-đi", "labelTH": "บุรุนดี", "labelAR": "بوروندي" },
    { "label": 'Cambodia', "value": '855', "labelKR": '캄보디아', "labelJP": "カンボジア", "labelCN": "柬埔寨", "labelVN": "Cam-pu-chia", "labelTH": "กัมพูชา", "labelAR": "كمبوديا" },
    { "label": 'Cameroon', "value": '237', "labelKR": '카메룬', "labelJP": "カメルーン", "labelCN": "喀麦隆", "labelVN": "Ca-mơ-run", "labelTH": "แคเมอรูน", "labelAR": "الكاميرون" },
    { "label": 'Cape Verde', "value": '238', "labelKR": '카보베르데', "labelJP": "カーボベルデ", "labelCN": "佛得角", "labelVN": "Cáp Vê", "labelTH": "เคปเวิร์ด", "labelAR": "الرأس الأخضر" },
    { "label": 'Cayman Islands', "value": '1345', "labelKR": '케이맨 제도', "labelJP": "ケイマン諸島", "labelCN": "开曼群岛", "labelVN": "Quần đảo Cayman", "labelTH": "หมู่เกาะเคย์แมน", "labelAR": "جزر كايمان" },
    { "label": 'Central Africa', "value": '236', "labelKR": '중앙 아프리카 공화국', "labelJP": "中央アフリカ共和国", "labelCN": "中非共和国", "labelVN": "Cộng hòa Trung Phi", "labelTH": "สาธารณรัฐแอฟริกากลาง", "labelAR": "جمهورية أفريقيا الوسطى" },
    { "label": 'Chad', "value": '235', "labelKR": '차드', "labelJP": "チャド", "labelCN": "乍得", "labelVN": "Sát", "labelTH": "ชาด", "labelAR": "تشاد" },
    { "label": 'Chile', "value": '56', "labelKR": '칠레', "labelJP": "チリ", "labelCN": "智利", "labelVN": "Chi-lê", "labelTH": "ชิลี", "labelAR": "تشيلي" },
    { "label": 'China', "value": '86', "labelKR": '중국', "labelJP": "中国", "labelCN": "中国", "labelVN": "Trung Quốc", "labelTH": "จีน", "labelAR": "الصين" },
    { "label": 'Colombia', "value": '57', "labelKR": '콜롬비아', "labelJP": "コロンビア", "labelCN": "哥伦比亚", "labelVN": "Cô-lôm-bi-a", "labelTH": "โคลอมเบีย", "labelAR": "كولومبيا" },
    { "label": 'Congo', "value": '242', "labelKR": '콩고', "labelJP": "コンゴ", "labelCN": "刚果", "labelVN": "Cộng hòa Congo", "labelTH": "คองโก", "labelAR": "الكونغو" },
    { "label": 'Cook Islands', "value": '682', "labelKR": '쿡 제도', "labelJP": "クック諸島", "labelCN": "库克群岛", "labelVN": "Quần đảo Cook", "labelTH": "หมู่เกาะคุก", "labelAR": "جزر كوك" },
    { "label": 'Costa Rica', "value": '506', "labelKR": '코스타리카', "labelJP": "コスタリカ", "labelCN": "哥斯达黎加", "labelVN": "Cô-xta Ri-ca", "labelTH": "คอสตาริกา", "labelAR": "كوستاريكا" },
    { "label": 'Croatia', "value": '385', "labelKR": '크로아티아', "labelJP": "クロアチア", "labelCN": "克罗地亚", "labelVN": "Crô-a-ti-a", "labelTH": "โครเอเชีย", "labelAR": "كرواتيا" },
    { "label": 'Cuba', "value": '53', "labelKR": '쿠바', "labelJP": "キューバ", "labelCN": "古巴", "labelVN": "Cu-ba", "labelTH": "คิวบา", "labelAR": "كوبا" },
    { "label": 'Cyprus', "value": '357', "labelKR": '키프로스', "labelJP": "キプロス", "labelCN": "塞浦路斯", "labelVN": "Síp", "labelTH": "ไซปรัส", "labelAR": "قبرص" },
    { "label": 'Czech', "value": '420', "labelKR": '체코', "labelJP": "チェコ", "labelCN": "捷克", "labelVN": "Séc", "labelTH": "เช็ก", "labelAR": "التشيك" },
    { "label": 'Denmark', "value": '45', "labelKR": '덴마크', "labelJP": "デンマーク", "labelCN": "丹麦", "labelVN": "Đan Mạch", "labelTH": "เดนมาร์ก", "labelAR": "الدنمارك" },
    { "label": 'Djibouti', "value": '253', "labelKR": '지부티', "labelJP": "ジブチ", "labelCN": "吉布提", "labelVN": "Gi-bu-ti", "labelTH": "จิบูตี", "labelAR": "جيبوتي" },
    { "label": 'Dominica', "value": '1767', "labelKR": '도미니카', "labelJP": "ドミニカ", "labelCN": "多米尼克", "labelVN": "Đô-mi-ni-ca", "labelTH": "โดมินิกา", "labelAR": "دومينيكا" },
    { "label": 'Dominican R.', "value": '1809', "labelKR": '도미니카 공화국', "labelJP": "ドミニカ共和国", "labelCN": "多米尼加共和国", "labelVN": "Cộng hòa Đô-mi-ni-ca", "labelTH": "สาธารณรัฐโดมินิกัน", "labelAR": "جمهورية الدومينيكان" },
    { "label": 'DPR of Korea', "value": '850', "labelKR": '조선민주주의인민공화국', "labelJP": "朝鮮民主主義人民共和国", "labelCN": "朝鲜民主主义人民共和国", "labelVN": "Cộng hòa Dân chủ Nhân dân Triều Tiên", "labelTH": "สาธารณรัฐประชาธิปไตยประชาชนเกาหลี", "labelAR": "جمهورية كوريا الديمقراطية الشعبية" },
    { "label": 'DR Congo', "value": '243', "labelKR": '콩고 민주 공화국', "labelJP": "コンゴ民主共和国", "labelCN": "刚果民主共和国", "labelVN": "Cộng hòa Dân chủ Congo", "labelTH": "สาธารณรัฐประชาธิปไตยคองโก", "labelAR": "جمهورية الكونغو الديمقراطية" },
    { "label": 'East Timor', "value": '670', "labelKR": '동티모르', "labelJP": "東ティモール", "labelCN": "东帝汶", "labelVN": "Đông Timor", "labelTH": "ติมอร์ตะวันออก", "labelAR": "تيمور الشرقية" },
    { "label": 'Ecuador', "value": '593', "labelKR": '에콰도르', "labelJP": "エクアドル", "labelCN": "厄瓜多尔", "labelVN": "Ecuador", "labelTH": "เอกวาดอร์", "labelAR": "الإكوادور" },
    { "label": 'Egypt', "value": '20', "labelKR": '이집트', "labelJP": "エジプト", "labelCN": "埃及", "labelVN": "Ai Cập", "labelTH": "อียิปต์", "labelAR": "مصر" },
    { "label": 'El Salvador', "value": '503', "labelKR": '엘살바도르', "labelJP": "エルサルバドル", "labelCN": "萨尔瓦多", "labelVN": "El Salvador", "labelTH": "เอลซัลวาดอร์", "labelAR": "السلفادور" },
    { "label": 'Equatorial Guinea', "value": '240', "labelKR": '적도 기니', "labelJP": "赤道ギニア", "labelCN": "赤道几内亚", "labelVN": "Guinea Xích Đạo", "labelTH": "อิเควทอเรียลกินี", "labelAR": "غينيا الاستوائية" },
    { "label": 'Eritrea', "value": '291', "labelKR": '에리트레아', "labelJP": "エリトリア", "labelCN": "厄立特里亚", "labelVN": "Eritrea", "labelTH": "เอริเทรีย", "labelAR": "إريتريا" },
    { "label": 'Estonia', "value": '372', "labelKR": '에스토니아', "labelJP": "エストニア", "labelCN": "爱沙尼亚", "labelVN": "Estonia", "labelTH": "เอสโตเนีย", "labelAR": "إستونيا" },
    { "label": 'Eswatini', "value": '268', "labelKR": '에스와티니', "labelJP": "エスワティニ", "labelCN": "斯威士兰", "labelVN": "Eswatini", "labelTH": "เอสวาตินี", "labelAR": "إسواتيني" },
    { "label": 'Ethiopia', "value": '251', "labelKR": '에티오피아', "labelJP": "エチオピア", "labelCN": "埃塞俄比亚", "labelVN": "Ethiopia", "labelTH": "เอธิโอเปีย", "labelAR": "إثيوبيا" },
    { "label": 'Falkland Islands', "value": '500', "labelKR": '포클랜드 제도', "labelJP": "フォークランド諸島", "labelCN": "福克兰群岛", "labelVN": "Quần đảo Falkland", "labelTH": "หมู่เกาะฟอล์กแลนด์", "labelAR": "جزر فوكلاند" },
    { "label": 'Fiji', "value": '679', "labelKR": '피지', "labelJP": "フィジー", "labelCN": "斐济", "labelVN": "Fiji", "labelTH": "ฟิจิ", "labelAR": "فيجي" },
    { "label": 'Finland', "value": '358', "labelKR": '핀란드', "labelJP": "フィンランド", "labelCN": "芬兰", "labelVN": "Phần Lan", "labelTH": "ฟินแลนด์", "labelAR": "فنلندا" },
    { "label": 'France', "value": '33', "labelKR": '프랑스', "labelJP": "フランス", "labelCN": "法国", "labelVN": "Pháp", "labelTH": "ฝรั่งเศส", "labelAR": "فرنسا" },
    { "label": 'Gabon', "value": '241', "labelKR": '가봉', "labelJP": "ガボン", "labelCN": "加蓬", "labelVN": "Gabon", "labelTH": "กาบอง", "labelAR": "الغابون" },
    { "label": 'Gambia', "value": '220', "labelKR": '감비아', "labelJP": "ガンビア", "labelCN": "冈比亚", "labelVN": "Gambia", "labelTH": "แกมเบีย", "labelAR": "غامبيا" },
    { "label": 'Georgia', "value": '995', "labelKR": '조지아', "labelJP": "ジョージア", "labelCN": "格鲁吉亚", "labelVN": "Georgia", "labelTH": "จอร์เจีย", "labelAR": "جورجيا" },
    { "label": 'Germany', "value": '49', "labelKR": '독일', "labelJP": "ドイツ", "labelCN": "德国", "labelVN": "Đức", "labelTH": "เยอรมนี", "labelAR": "ألمانيا" },
    { "label": 'Ghana', "value": '233', "labelKR": '가나', "labelJP": "ガーナ", "labelCN": "加纳", "labelVN": "Ghana", "labelTH": "กานา", "labelAR": "غانا" },
    { "label": 'Gibraltar', "value": '350', "labelKR": '지브롤터', "labelJP": "ジブラルタル", "labelCN": "直布罗陀", "labelVN": "Gibraltar", "labelTH": "ยิบรอลตาร์", "labelAR": "جبل طارق" },
    { "label": 'Greece', "value": '30', "labelKR": '그리스', "labelJP": "ギリシャ", "labelCN": "希腊", "labelVN": "Hy Lạp", "labelTH": "กรีซ", "labelAR": "اليونان" },
    { "label": 'Greenland', "value": '299', "labelKR": '그린란드', "labelJP": "グリーンランド", "labelCN": "格陵兰", "labelVN": "Greenland", "labelTH": "กรีนแลนด์", "labelAR": "جرينلاند" },
    { "label": 'Grenada', "value": '1473', "labelKR": '그레나다', "labelJP": "グレナダ", "labelCN": "格林纳达", "labelVN": "Grenada", "labelTH": "เกรเนดา", "labelAR": "غرينادا" },
    { "label": 'Guadeloupe', "value": '590', "labelKR": '과들루프', "labelJP": "グアドループ", "labelCN": "瓜德罗普", "labelVN": "Guadeloupe", "labelTH": "กวาเดอลูป", "labelAR": "جوادلوب" },
    { "label": 'Guam', "value": '1671', "labelKR": '괌', "labelJP": "グアム", "labelCN": "关岛", "labelVN": "Guam", "labelTH": "กวม", "labelAR": "غوام" },
    { "label": 'Guatemala', "value": '502', "labelKR": '과테말라', "labelJP": "グアテマラ", "labelCN": "危地马拉", "labelVN": "Guatemala", "labelTH": "กัวเตมาลา", "labelAR": "غواتيمالا" },
    { "label": 'Guinea', "value": '224', "labelKR": '기니', "labelJP": "ギニア", "labelCN": "几内亚", "labelVN": "Guinea", "labelTH": "กินี", "labelAR": "غينيا" },
    { "label": 'Guinea-Bissau', "value": '245', "labelKR": '기니비사우', "labelJP": "ギニアビサウ", "labelCN": "几内亚比绍", "labelVN": "Guinea-Bissau", "labelTH": "กินี-บิสเซา", "labelAR": "غينيا بيساو" },
    { "label": 'Guyana', "value": '592', "labelKR": '가이아나', "labelJP": "ガイアナ", "labelCN": "圭亚那", "labelVN": "Guyana", "labelTH": "กายอานา", "labelAR": "غيانا" },
    { "label": "Haiti", "value": "509", "labelKR": "아이티", "labelJP": "ハイチ", "labelCN": "海地", "labelVN": "Haiti", "labelTH": "เฮติ", "labelAR": "هايتي" },
    { "label": "Honduras", "value": "504", "labelKR": "온두라스", "labelJP": "ホンジュラス", "labelCN": "洪都拉斯", "labelVN": "Honduras", "labelTH": "ฮอนดูรัส", "labelAR": "هندوراس" },
    { "label": "Hong Kong", "value": "852", "labelKR": "홍콩", "labelJP": "香港", "labelCN": "香港", "labelVN": "Hồng Kông", "labelTH": "ฮ่องกง", "labelAR": "هونغ كونغ" },
    { "label": "Hungary", "value": "36", "labelKR": "헝가리", "labelJP": "ハンガリー", "labelCN": "匈牙利", "labelVN": "Hungary", "labelTH": "ฮังการี", "labelAR": "هنغاريا" },
    { "label": "Iceland", "value": "354", "labelKR": "아이슬란드", "labelJP": "アイスランド", "labelCN": "冰岛", "labelVN": "Iceland", "labelTH": "ไอซ์แลนด์", "labelAR": "آيسلندا" },
    { "label": "India", "value": "91", "labelKR": "인도", "labelJP": "インド", "labelCN": "印度", "labelVN": "Ấn Độ", "labelTH": "อินเดีย", "labelAR": "الهند" },
    { "label": "Indonesia", "value": "62", "labelKR": "인도네시아", "labelJP": "インドネシア", "labelCN": "印度尼西亚", "labelVN": "Indonesia", "labelTH": "อินโดนีเซีย", "labelAR": "إندونيسيا" },
    { "label": "Iran", "value": "98", "labelKR": "이란", "labelJP": "イラン", "labelCN": "伊朗", "labelVN": "Iran", "labelTH": "อิหร่าน", "labelAR": "إيران" },
    { "label": "Iraq", "value": "964", "labelKR": "이라크", "labelJP": "イラク", "labelCN": "伊拉克", "labelVN": "Iraq", "labelTH": "อิรัก", "labelAR": "العراق" },
    { "label": "Ireland", "value": "353", "labelKR": "아일랜드", "labelJP": "アイルランド", "labelCN": "爱尔兰", "labelVN": "Ireland", "labelTH": "ไอร์แลนด์", "labelAR": "أيرلندا" },
    { "label": "Israel", "value": "972", "labelKR": "이스라엘", "labelJP": "イスラエル", "labelCN": "以色列", "labelVN": "Israel", "labelTH": "อิสราเอล", "labelAR": "إسرائيل" },
    { "label": "Italy", "value": "39", "labelKR": "이탈리아", "labelJP": "イタリア", "labelCN": "意大利", "labelVN": "Italy", "labelTH": "อิตาลี", "labelAR": "إيطاليا" },
    { "label": "Ivory Coast", "value": "225", "labelKR": "코트디부아르", "labelJP": "コートジボワール", "labelCN": "科特迪瓦", "labelVN": "Bờ Biển Ngà", "labelTH": "ไอวอรีโคสต์", "labelAR": "ساحل العاج" },
    { "label": "Jamaica", "value": "1876", "labelKR": "자메이카", "labelJP": "ジャマイカ", "labelCN": "牙买加", "labelVN": "Jamaica", "labelTH": "จาเมกา", "labelAR": "جامايكا" },
    { "label": "Japan", "value": "81", "labelKR": "일본", "labelJP": "日本", "labelCN": "日本", "labelVN": "Nhật Bản", "labelTH": "ญี่ปุ่น", "labelAR": "اليابان" },
    { "label": "Jordan", "value": "962", "labelKR": "요르단", "labelJP": "ヨルダン", "labelCN": "约旦", "labelVN": "Jordan", "labelTH": "จอร์แดน", "labelAR": "الأردن" },
    { "label": "Kazakhstan", "value": "7", "labelKR": "카자흐스탄", "labelJP": "カザフスタン", "labelCN": "哈萨克斯坦", "labelVN": "Kazakhstan", "labelTH": "คาซัคสถาน", "labelAR": "كازاخستان" },
    { "label": "Kenya", "value": "254", "labelKR": "케냐", "labelJP": "ケニア", "labelCN": "肯尼亚", "labelVN": "Kenya", "labelTH": "เคนยา", "labelAR": "كينيا" },
    { "label": "Kiribati", "value": "686", "labelKR": "키리바시", "labelJP": "キリバス", "labelCN": "基里巴斯", "labelVN": "Kiribati", "labelTH": "คิริบาส", "labelAR": "كيريباس" },
    { "label": "Kuwait", "value": "965", "labelKR": "쿠웨이트", "labelJP": "クウェート", "labelCN": "科威特", "labelVN": "Kuwait", "labelTH": "คูเวต", "labelAR": "الكويت" },
    { "label": "Kyrgyzstan", "value": "996", "labelKR": "키르기스스탄", "labelJP": "キルギス", "labelCN": "吉尔吉斯斯坦", "labelVN": "Kyrgyzstan", "labelTH": "คีร์กีซสถาน", "labelAR": "قرغيزستان" },
    { "label": "Laos", "value": "856", "labelKR": "라오스", "labelJP": "ラオス", "labelCN": "老挝", "labelVN": "Lào", "labelTH": "ลาว", "labelAR": "لاوس" },
    { "label": "Latvia", "value": "371", "labelKR": "라트비아", "labelJP": "ラトビア", "labelCN": "拉脱维亚", "labelVN": "Latvia", "labelTH": "ลัตเวีย", "labelAR": "لاتفيا" },
    { "label": "Lebanon", "value": "961", "labelKR": "레바논", "labelJP": "レバノン", "labelCN": "黎巴嫩", "labelVN": "Lebanon", "labelTH": "เลบานอน", "labelAR": "لبنان" },
    { "label": "Lesotho", "value": "266", "labelKR": "레소토", "labelJP": "レソト", "labelCN": "莱索托", "labelVN": "Lesotho", "labelTH": "เลโซโท", "labelAR": "ليسوتو" },
    { "label": "Liberia", "value": "231", "labelKR": "라이베리아", "labelJP": "リベリア", "labelCN": "利比里亚", "labelVN": "Liberia", "labelTH": "ไลบีเรีย", "labelAR": "ليبيريا" },
    { "label": "Libya", "value": "218", "labelKR": "리비아", "labelJP": "リビア", "labelCN": "利比亚", "labelVN": "Libya", "labelTH": "ลิเบีย", "labelAR": "ليبيا" },
    { "label": "Liechtenstein", "value": "423", "labelKR": "리히텐슈타인", "labelJP": "リヒテンシュタイン", "labelCN": "列支敦士登", "labelVN": "Liechtenstein", "labelTH": "ลิกเตนสไตน์", "labelAR": "ليختنشتاين" },
    { "label": "Lithuania", "value": "370", "labelKR": "리투아니아", "labelJP": "リトアニア", "labelCN": "立陶宛", "labelVN": "Lithuania", "labelTH": "ลิทัวเนีย", "labelAR": "ليتوانيا" },
    { "label": "Luxembourg", "value": "352", "labelKR": "룩셈부르크", "labelJP": "ルクセンブルク", "labelCN": "卢森堡", "labelVN": "Luxembourg", "labelTH": "ลักเซมเบิร์ก", "labelAR": "لوكسمبورغ" },
    { "label": 'Macao', "value": '853', "labelKR": '마카오', "labelJP": 'マカオ', "labelCN": '澳门', "labelVN": 'Ma Cao', "labelTH": 'มาเก๊า', "labelAR": 'ماكاو' },
    { "label": 'Macedonia', "value": '389', "labelKR": '북마케도니아', "labelJP": 'マケドニア', "labelCN": '北马其顿', "labelVN": 'Macédonie', "labelTH": 'มาซิโดเนีย', "labelAR": 'مقدونيا' },
    { "label": 'Madagascar', "value": '261', "labelKR": '마다가스카르', "labelJP": 'マダガスカル', "labelCN": '马达加斯加', "labelVN": 'Madagascar', "labelTH": 'มาดากัสการ์', "labelAR": 'مدغشقر' },
    { "label": 'Malawi', "value": '265', "labelKR": '말라위', "labelJP": 'マラウイ', "labelCN": '马拉维', "labelVN": 'Malawi', "labelTH": 'มาลาวี', "labelAR": 'مالاوي' },
    { "label": 'Malaysia', "value": '60', "labelKR": '말레이시아', "labelJP": 'マレーシア', "labelCN": '马来西亚', "labelVN": 'Malaysia', "labelTH": 'มาเลเซีย', "labelAR": 'ماليزيا' },
    { "label": 'Maldives', "value": '960', "labelKR": '몰디브', "labelJP": 'モルディブ', "labelCN": '马尔代夫', "labelVN": 'Maldives', "labelTH": 'มัลดีฟส์', "labelAR": 'جزر المالديف' },
    { "label": 'Moldova', "value": '373', "labelKR": '몰도바', "labelJP": 'モルドバ', "labelCN": '摩尔多瓦', "labelVN": 'Moldova', "labelTH": 'มอลโดวา', "labelAR": 'مولدوفا' },
    { "label": 'Mali', "value": '223', "labelKR": '말리', "labelJP": 'マリ', "labelCN": '马里', "labelVN": 'Mali', "labelTH": 'มาลี', "labelAR": 'مالي' },
    { "label": 'Malta', "value": '356', "labelKR": '몰타', "labelJP": 'マルタ', "labelCN": '马耳他', "labelVN": 'Malta', "labelTH": 'มอลตา', "labelAR": 'مالطا' },
    { "label": 'Marshall Islands', "value": '692', "labelKR": '마셜 제도', "labelJP": 'マーシャル諸島', "labelCN": '马绍尔群岛', "labelVN": 'Quần đảo Marshall', "labelTH": 'หมู่เกาะมาร์แชล', "labelAR": 'جزر مارشال' },
    { "label": 'Martinique', "value": '596', "labelKR": '마르티니크', "labelJP": 'マルティニーク', "labelCN": '马提尼克', "labelVN": 'Martinique', "labelTH": 'มาร์ตินีก', "labelAR": 'مارتينيك' },
    { "label": 'Mauritania', "value": '222', "labelKR": '모리타니', "labelJP": 'モーリタニア', "labelCN": '毛里塔尼亚', "labelVN": 'Mauritania', "labelTH": 'มอริเตเนีย', "labelAR": 'موريتانيا' },
    { "label": 'Mauritius', "value": '230', "labelKR": '모리셔스', "labelJP": 'モーリシャス', "labelCN": '毛里求斯', "labelVN": 'Mauritius', "labelTH": 'มอริเชียส', "labelAR": 'موريشيوس' },
    { "label": 'Mayotte', "value": '269', "labelKR": '마요트', "labelJP": 'マヨット', "labelCN": '马约特', "labelVN": 'Mayotte', "labelTH": 'มายอต', "labelAR": 'مايوت' },
    { "label": 'Mexico', "value": '52', "labelKR": '멕시코', "labelJP": 'メキシコ', "labelCN": '墨西哥', "labelVN": 'Mexico', "labelTH": 'เม็กซิโก', "labelAR": 'المكسيك' },
    { "label": 'Micronesia', "value": '691', "labelKR": '미크로네시아', "labelJP": 'ミクロネシア', "labelCN": '密克罗尼西亚', "labelVN": 'Micronesia', "labelTH": 'ไมโครนีเซีย', "labelAR": 'ميكرونيزيا' },
    { "label": 'Monaco', "value": '377', "labelKR": '모나코', "labelJP": 'モナコ', "labelCN": '摩纳哥', "labelVN": 'Monaco', "labelTH": 'โมนาโก', "labelAR": 'موناكو' },
    { "label": 'Mongolia', "value": '976', "labelKR": '몽골', "labelJP": 'モンゴル', "labelCN": '蒙古', "labelVN": 'Mông Cổ', "labelTH": 'มองโกเลีย', "labelAR": 'منغوليا' },
    { "label": 'Montenegro', "value": '382', "labelKR": '몬테네그로', "labelJP": 'モンテネグロ', "labelCN": '黑山', "labelVN": 'Montenegro', "labelTH": 'มอนเตเนโกร', "labelAR": 'مونتينيغرو' },
    { "label": 'Montserrat', "value": '1664', "labelKR": '몬트세랫', "labelJP": 'モントセラト', "labelCN": '蒙特塞拉特', "labelVN": 'Montserrat', "labelTH": 'มอนต์เซอร์รัต', "labelAR": 'مونتسيرات' },
    { "label": 'Morocco', "value": '212', "labelKR": '모로코', "labelJP": 'モロッコ', "labelCN": '摩洛哥', "labelVN": 'Morocco', "labelTH": 'โมร็อกโก', "labelAR": 'المغرب' },
    { "label": 'Mozambique', "value": '258', "labelKR": '모잠비크', "labelJP": 'モザンビーク', "labelCN": '莫桑比克', "labelVN": 'Mozambique', "labelTH": 'โมซัมบิก', "labelAR": 'موزمبيق' },
    { "label": 'Myanmar', "value": '95', "labelKR": '미얀마', "labelJP": 'ミャンマー', "labelCN": '缅甸', "labelVN": 'Myanmar', "labelTH": 'เมียนมาร์', "labelAR": 'ميانمار' },
    { "label": 'Namibia', "value": '264', "labelKR": '나미비아', "labelJP": 'ナミビア', "labelCN": '纳米比亚', "labelVN": 'Namibia', "labelTH": 'นามิเบีย', "labelAR": 'ناميبيا' },
    { "label": 'Nauru', "value": '674', "labelKR": '나우루', "labelJP": 'ナウル', "labelCN": '瑙鲁', "labelVN": 'Nauru', "labelTH": 'นาอูรู', "labelAR": 'ناورو' },
    { "label": 'Nepal', "value": '977', "labelKR": '네팔', "labelJP": 'ネパール', "labelCN": '尼泊尔', "labelVN": 'Nepal', "labelTH": 'เนปาล', "labelAR": 'نيبال' },
    { "label": 'New Caledonia', "value": '687', "labelKR": '뉴칼레도니아', "labelJP": 'ニューカレドニア', "labelCN": '新喀里多尼亚', "labelVN": 'New Caledonia', "labelTH": 'นิวแคลิโดเนีย', "labelAR": 'كاليدونيا الجديدة' },
    { "label": 'New Zealand', "value": '64', "labelKR": '뉴질랜드', "labelJP": 'ニュージーランド', "labelCN": '新西兰', "labelVN": 'New Zealand', "labelTH": 'นิวซีแลนด์', "labelAR": 'نيوزيلندا' },
    { "label": 'Nicaragua', "value": '505', "labelKR": '니카라과', "labelJP": 'ニカラグア', "labelCN": '尼加拉瓜', "labelVN": 'Nicaragua', "labelTH": 'นิการากัว', "labelAR": 'نيكاراغوا' },
    { "label": 'Niger', "value": '227', "labelKR": '니제르', "labelJP": 'ニジェール', "labelCN": '尼日尔', "labelVN": 'Niger', "labelTH": 'ไนเจอร์', "labelAR": 'النيجر' },
    { "label": 'Nigeria', "value": '234', "labelKR": '나이지리아', "labelJP": 'ナイジェリア', "labelCN": '尼日利亚', "labelVN": 'Nigeria', "labelTH": 'ไนจีเรีย', "labelAR": 'نيجيريا' },
    { "label": 'Niue', "value": '683', "labelKR": '니우에', "labelJP": 'ニウエ', "labelCN": '纽埃', "labelVN": 'Niue', "labelTH": 'นีอูเอ', "labelAR": 'نيوي' },
    { "label": 'Norway', "value": '47', "labelKR": '노르웨이', "labelJP": 'ノルウェー', "labelCN": '挪威', "labelVN": 'Norway', "labelTH": 'นอร์เวย์', "labelAR": 'النرويج' },
    { "label": "Oman", "value": "968", "labelKR": "오만", "labelJP": "オマーン", "labelCN": "阿曼", "labelVN": "Ô-man", "labelTH": "โอมาน", "labelAR": "عُمان" },
    { "label": "Pakistan", "value": "92", "labelKR": "파키스탄", "labelJP": "パキスタン", "labelCN": "巴基斯坦", "labelVN": "Pakistan", "labelTH": "ปากีสถาน", "labelAR": "باكستان" },
    { "label": "Palau", "value": "680", "labelKR": "팔라우", "labelJP": "パラオ", "labelCN": "帕劳", "labelVN": "Palau", "labelTH": "ปาเลา", "labelAR": "بالاو" },
    { "label": "Panama", "value": "507", "labelKR": "파나마", "labelJP": "パナマ", "labelCN": "巴拿马", "labelVN": "Panama", "labelTH": "ปานามา", "labelAR": "بنما" },
    { "label": "Papua New Guinea", "value": "675", "labelKR": "파푸아뉴기니", "labelJP": "パプアニューギニア", "labelCN": "巴布亚新几内亚", "labelVN": "Papua New Guinea", "labelTH": "ปาปัวนิวกินี", "labelAR": "بابوا غينيا الجديدة" },
    { "label": "Paraguay", "value": "595", "labelKR": "파라과이", "labelJP": "パラグアイ", "labelCN": "巴拉圭", "labelVN": "Paraguay", "labelTH": "ปารากวัย", "labelAR": "باراغواي" },
    { "label": "Peru", "value": "51", "labelKR": "페루", "labelJP": "ペルー", "labelCN": "秘鲁", "labelVN": "Peru", "labelTH": "เปรู", "labelAR": "بيرو" },
    { "label": "Poland", "value": "48", "labelKR": "폴란드", "labelJP": "ポーランド", "labelCN": "波兰", "labelVN": "Ba Lan", "labelTH": "โปแลนด์", "labelAR": "بولندا" },
    { "label": "Portugal", "value": "351", "labelKR": "포르투갈", "labelJP": "ポルトガル", "labelCN": "葡萄牙", "labelVN": "Bồ Đào Nha", "labelTH": "โปรตุเกส", "labelAR": "البرتغال" },
    { "label": "Puerto Rico", "value": "1787", "labelKR": "푸에르토리코", "labelJP": "プエルトリコ", "labelCN": "波多黎各", "labelVN": "Puerto Rico", "labelTH": "เปอร์โตริโก", "labelAR": "بورتو ريكو" },
    { "label": "Qatar", "value": "974", "labelKR": "카타르", "labelJP": "カタール", "labelCN": "卡塔尔", "labelVN": "Qatar", "labelTH": "กาตาร์", "labelAR": "قطر" },
    { "label": "Republic of Korea", "value": "82", "labelKR": "대한민국", "labelJP": "大韓民国", "labelCN": "韩国", "labelVN": "Hàn Quốc", "labelTH": "สาธารณรัฐเกาหลี", "labelAR": "جمهورية كوريا" },
    { "label": "Romania", "value": "40", "labelKR": "루마니아", "labelJP": "ルーマニア", "labelCN": "罗马尼亚", "labelVN": "Romania", "labelTH": "โรมาเนีย", "labelAR": "رومانيا" },
    { "label": "Russia", "value": "7", "labelKR": "러시아", "labelJP": "ロシア", "labelCN": "俄罗斯", "labelVN": "Nga", "labelTH": "รัสเซีย", "labelAR": "روسيا" },
    { "label": "Rwanda", "value": "250", "labelKR": "르완다", "labelJP": "ルワンダ", "labelCN": "卢旺达", "labelVN": "Rwanda", "labelTH": "รวันดา", "labelAR": "رواندا" },
    { "label": "Saint Helena", "value": "290", "labelKR": "세인트 헬레나", "labelJP": "セントヘレナ", "labelCN": "圣赫勒拿", "labelVN": "Saint Helena", "labelTH": "เซนต์เฮเลนา", "labelAR": "سانت هيلينا" },
    { "label": "Saint Lucia", "value": "1758", "labelKR": "세인트루시아", "labelJP": "セントルシア", "labelCN": "圣卢西亚", "labelVN": "Saint Lucia", "labelTH": "เซนต์ลูเซีย", "labelAR": "سانت لوسيا" },
    { "label": "Saint Pierre and Miquelon", "value": "508", "labelKR": "생피에르 미클롱", "labelJP": "サンピエール・ミクロン", "labelCN": "圣皮埃尔和密克隆", "labelVN": "Saint Pierre and Miquelon", "labelTH": "แซงปิแอร์และมีเกอลอน", "labelAR": "سان بيير وميكلون" },
    { "label": "Samoa", "value": "685", "labelKR": "사모아", "labelJP": "サモア", "labelCN": "萨摩亚", "labelVN": "Samoa", "labelTH": "ซามัว", "labelAR": "ساموا" },
    { "label": "San Marino", "value": "378", "labelKR": "산마리노", "labelJP": "サンマリノ", "labelCN": "圣马力诺", "labelVN": "San Marino", "labelTH": "ซานมารีโน", "labelAR": "سان مارينو" },
    { "label": "Saudi Arabia", "value": "966", "labelKR": "사우디아라비아", "labelJP": "サウジアラビア", "labelCN": "沙特阿拉伯", "labelVN": "Ả Rập Xê-út", "labelTH": "ซาอุดีอาระเบีย", "labelAR": "المملكة العربية السعودية" },
    { "label": "Senegal", "value": "221", "labelKR": "세네갈", "labelJP": "セネガル", "labelCN": "塞内加尔", "labelVN": "Senegal", "labelTH": "เซเนกัล", "labelAR": "السنغال" },
    { "label": "Serbia", "value": "381", "labelKR": "세르비아", "labelJP": "セルビア", "labelCN": "塞尔维亚", "labelVN": "Serbia", "labelTH": "เซอร์เบีย", "labelAR": "صربيا" },
    { "label": "Seychelles", "value": "248", "labelKR": "세이셸", "labelJP": "セーシェル", "labelCN": "塞舌尔", "labelVN": "Seychelles", "labelTH": "เซเชลส์", "labelAR": "سيشيل" },
    { "label": "Sierra Leone", "value": "232", "labelKR": "시에라리온", "labelJP": "シエラレオネ", "labelCN": "塞拉利昂", "labelVN": "Sierra Leone", "labelTH": "เซียร์ราลีโอน", "labelAR": "سيراليون" },
    { "label": "Singapore", "value": "65", "labelKR": "싱가포르", "labelJP": "シンガポール", "labelCN": "新加坡", "labelVN": "Singapore", "labelTH": "สิงคโปร์", "labelAR": "سنغافورة" },
    { "label": "Sint Maarten", "value": "1721", "labelKR": "신트마르턴", "labelJP": "シント・マールテン", "labelCN": "圣马丁岛", "labelVN": "Sint Maarten", "labelTH": "ซินต์มาร์เทิน", "labelAR": "سينت مارتن" },
    { "label": "Slovakia", "value": "421", "labelKR": "슬로바키아", "labelJP": "スロバキア", "labelCN": "斯洛伐克", "labelVN": "Slovakia", "labelTH": "สโลวาเกีย", "labelAR": "سلوفاكيا" },
    { "label": "Slovenia", "value": "386", "labelKR": "슬로베니아", "labelJP": "スロベニア", "labelCN": "斯洛文尼亚", "labelVN": "Slovenia", "labelTH": "สโลวีเนีย", "labelAR": "سلوفينيا" },
    { "label": "Solomon Islands", "value": "677", "labelKR": "솔로몬 제도", "labelJP": "ソロモン諸島", "labelCN": "所罗门群岛", "labelVN": "Quần đảo Solomon", "labelTH": "หมู่เกาะโซโลมอน", "labelAR": "جزر سليمان" },
    { "label": "Somalia", "value": "252", "labelKR": "소말리아", "labelJP": "ソマリア", "labelCN": "索马里", "labelVN": "Somalia", "labelTH": "โซมาเลีย", "labelAR": "الصومال" },
    { "label": "South Africa", "value": "27", "labelKR": "남아프리카공화국", "labelJP": "南アフリカ", "labelCN": "南非", "labelVN": "Nam Phi", "labelTH": "แอฟริกาใต้", "labelAR": "جنوب أفريقيا" },
    { "label": "South Sudan", "value": "211", "labelKR": "남수단", "labelJP": "南スーダン", "labelCN": "南苏丹", "labelVN": "Nam Sudan", "labelTH": "ซูดานใต้", "labelAR": "جنوب السودان" },
    { "label": "Spain", "value": "34", "labelKR": "스페인", "labelJP": "スペイン", "labelCN": "西班牙", "labelVN": "Tây Ban Nha", "labelTH": "สเปน", "labelAR": "إسبانيا" },
    { "label": "Sri Lanka", "value": "94", "labelKR": "스리랑카", "labelJP": "スリランカ", "labelCN": "斯里兰卡", "labelVN": "Sri Lanka", "labelTH": "ศรีลังกา", "labelAR": "سريلانكا" },
    { "label": "State of Palestine", "value": "970", "labelKR": "팔레스타인", "labelJP": "パレスチナ", "labelCN": "巴勒斯坦", "labelVN": "Palestine", "labelTH": "ปาเลสไตน์", "labelAR": "دولة فلسطين" },
    { "label": "Sudan", "value": "249", "labelKR": "수단", "labelJP": "スーダン", "labelCN": "苏丹", "labelVN": "Soudan", "labelTH": "ซูดาน", "labelAR": "السودان" },
    { "label": "Suriname", "value": "597", "labelKR": "수리남", "labelJP": "スリナム", "labelCN": "苏里南", "labelVN": "Suriname", "labelTH": "ซูรินาเม", "labelAR": "سورينام" },
    { "label": "Sweden", "value": "46", "labelKR": "스웨덴", "labelJP": "スウェーデン", "labelCN": "瑞典", "labelVN": "Thụy Điển", "labelTH": "สวีเดน", "labelAR": "السويد" },
    { "label": "Switzerland", "value": "41", "labelKR": "스위스", "labelJP": "スイス", "labelCN": "瑞士", "labelVN": "Thụy Sĩ", "labelTH": "สวิตเซอร์แลนด์", "labelAR": "سويسرا" },
    { "label": "Syria", "value": "963", "labelKR": "시리아", "labelJP": "シリア", "labelCN": "叙利亚", "labelVN": "Syria", "labelTH": "ซีเรีย", "labelAR": "سوريا" },
    { "label": "Taiwan", "value": "886", "labelKR": "대만", "labelJP": "台湾", "labelCN": "台湾", "labelVN": "Đài Loan", "labelTH": "ไต้หวัน", "labelAR": "تايوان" },
    { "label": "Tajikistan", "value": "992", "labelKR": "타지키스탄", "labelJP": "タジキスタン", "labelCN": "塔吉克斯坦", "labelVN": "Tajikistan", "labelTH": "ทาจิกิสถาน", "labelAR": "طاجيكستان" },
    { "label": "Tanzania", "value": "255", "labelKR": "탄자니아", "labelJP": "タンザニア", "labelCN": "坦桑尼亚", "labelVN": "Tanzania", "labelTH": "แทนซาเนีย", "labelAR": "تنزانيا" },
    { "label": "Thailand", "value": "66", "labelKR": "태국", "labelJP": "タイ", "labelCN": "泰国", "labelVN": "Thái Lan", "labelTH": "ประเทศไทย", "labelAR": "تايلاند" },
    { "label": "Comoros", "value": "269", "labelKR": "코모로", "labelJP": "コモロ", "labelCN": "科摩罗", "labelVN": "Comoros", "labelTH": "โคโมรอส", "labelAR": "جزر القمر" },
    { "label": "Netherlands", "value": "31", "labelKR": "네덜란드", "labelJP": "オランダ", "labelCN": "荷兰", "labelVN": "Hà Lan", "labelTH": "เนเธอร์แลนด์", "labelAR": "هولندا" },
    { "label": "Philippines", "value": "63", "labelKR": "필리핀", "labelJP": "フィリピン", "labelCN": "菲律宾", "labelVN": "Philippines", "labelTH": "ฟิลิปปินส์", "labelAR": "الفلبين" },
    { "label": "Togo", "value": "228", "labelKR": "토고", "labelJP": "トーゴ", "labelCN": "多哥", "labelVN": "Togo", "labelTH": "โตโก", "labelAR": "توجو" },
    { "label": "Tokelau", "value": "690", "labelKR": "토켈라우", "labelJP": "トケラウ", "labelCN": "托克劳", "labelVN": "Tokelau", "labelTH": "โทเคลาอู", "labelAR": "توكيلاو" },
    { "label": "Tonga", "value": "676", "labelKR": "통가", "labelJP": "トンガ", "labelCN": "汤加", "labelVN": "Tonga", "labelTH": "ตองกา", "labelAR": "تونغا" },
    { "label": "Trinidad and Tobago", "value": "1868", "labelKR": "트리니다드 토바고", "labelJP": "トリニダード・トバゴ", "labelCN": "特立尼达和多巴哥", "labelVN": "Trinidad và Tobago", "labelTH": "ตรินิแดดและโตเบโก", "labelAR": "ترينيداد وتوباغو" },
    { "label": "Tunisia", "value": "216", "labelKR": "튀니지", "labelJP": "チュニジア", "labelCN": "突尼斯", "labelVN": "Tunisia", "labelTH": "ตูนิเซีย", "labelAR": "تونس" },
    { "label": "Turkey", "value": "90", "labelKR": "튀르키예", "labelJP": "トルコ", "labelCN": "土耳其", "labelVN": "Thổ Nhĩ Kỳ", "labelTH": "ตุรกี", "labelAR": "تركيا" },
    { "label": "Turkmenistan", "value": "993", "labelKR": "투르크메니스탄", "labelJP": "トルクメニスタン", "labelCN": "土库曼斯坦", "labelVN": "Turkmenistan", "labelTH": "เติร์กเมนิสถาน", "labelAR": "تركمانستان" },
    { "label": "Tuvalu", "value": "688", "labelKR": "투발루", "labelJP": "ツバル", "labelCN": "图瓦卢", "labelVN": "Tuvalu", "labelTH": "ตูวาลู", "labelAR": "توفالو" },
    { "label": "Uganda", "value": "256", "labelKR": "우간다", "labelJP": "ウガンダ", "labelCN": "乌干达", "labelVN": "Uganda", "labelTH": "ยูกันดา", "labelAR": "أوغندا" },
    { "label": "Ukraine", "value": "380", "labelKR": "우크라이나", "labelJP": "ウクライナ", "labelCN": "乌克兰", "labelVN": "Ukraina", "labelTH": "ยูเครน", "labelAR": "أوكرانيا" },
    { "label": "United Arab Emirates", "value": "971", "labelKR": "아랍에미리트", "labelJP": "アラブ首長国連邦", "labelCN": "阿联酋", "labelVN": "Các Tiểu vương quốc Ả Rập thống nhất", "labelTH": "สหรัฐอาหรับเอมิเรตส์", "labelAR": "الإمارات العربية المتحدة" },
    { "label": "United Kingdom", "value": "44", "labelKR": "영국", "labelJP": "イギリス", "labelCN": "英国", "labelVN": "Vương quốc Anh", "labelTH": "สหราชอาณาจักร", "labelAR": "المملكة المتحدة" },
    { "label": "United States of America & Canada", "value": "1", "labelKR": "미국 & 캐나다", "labelJP": "アメリカ & カナダ", "labelCN": "美国 & 加拿大", "labelVN": "Hoa Kỳ & Canada", "labelTH": "สหรัฐอเมริกา & แคนาดา", "labelAR": "الولايات المتحدة الأمريكية وكندا" },
    { "label": "Uruguay", "value": "598", "labelKR": "우루과이", "labelJP": "ウルグアイ", "labelCN": "乌拉圭", "labelVN": "Uruguay", "labelTH": "อุรุกวัย", "labelAR": "أوروغواي" },
    { "label": "Uzbekistan", "value": "998", "labelKR": "우즈베키스탄", "labelJP": "ウズベキスタン", "labelCN": "乌兹别克斯坦", "labelVN": "Uzbekistan", "labelTH": "อุซเบกิสถาน", "labelAR": "أوزبكستان" },
    { "label": "Vanuatu", "value": "678", "labelKR": "바누아투", "labelJP": "バヌアツ", "labelCN": "瓦努阿图", "labelVN": "Vanuatu", "labelTH": "วานูอาตู", "labelAR": "فانواتو" },
    { "label": "Vatican", "value": "379", "labelKR": "바티칸", "labelJP": "バチカン", "labelCN": "梵蒂冈", "labelVN": "Vatican", "labelTH": "นครวาติกัน", "labelAR": "الفاتيكان" },
    { "label": "Venezuela", "value": "58", "labelKR": "베네수엘라", "labelJP": "ベネズエラ", "labelCN": "委内瑞拉", "labelVN": "Venezuela", "labelTH": "เวเนซุเอลา", "labelAR": "فنزويلا" },
    { "label": "Vietnam", "value": "84", "labelKR": "베트남", "labelJP": "ベトナム", "labelCN": "越南", "labelVN": "Việt Nam", "labelTH": "เวียดนาม", "labelAR": "فيتنام" },
    { "label": "Western Sahara", "value": "212", "labelKR": "서사하라", "labelJP": "西サハラ", "labelCN": "西撒哈拉", "labelVN": "Sahara Tây", "labelTH": "ซาฮาราตะวันตก", "labelAR": "الصحراء الغربية" },
    { "label": "Yemen", "value": "967", "labelKR": "예멘", "labelJP": "イエメン", "labelCN": "也门", "labelVN": "Yemen", "labelTH": "เยเมน", "labelAR": "اليمن" },
    { "label": "Zambia", "value": "260", "labelKR": "잠비아", "labelJP": "ザンビア", "labelCN": "赞比亚", "labelVN": "Zambia", "labelTH": "แซมเบีย", "labelAR": "زامبيا" },
    { "label": "Zimbabwe", "value": "263", "labelKR": "짐바브웨", "labelJP": "ジンバブエ", "labelCN": "津巴布韦", "labelVN": "Zimbabwe", "labelTH": "ซิมบับเว", "labelAR": "زيمبابوي" },
  ];
}